// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by hack/docgen tool. DO NOT EDIT.

package extensions

import (
	"github.com/siderolabs/talos/pkg/machinery/config/encoder"
)

func (ServiceConfigV1Alpha1) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "ExtensionServiceConfig",
		Comments:    [3]string{"" /* encoder.HeadComment */, "ExtensionServiceConfig is a extensionserviceconfig document." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "ExtensionServiceConfig is a extensionserviceconfig document.",
		Fields: []encoder.Doc{
			{
				Type:   "Meta",
				Inline: true,
			},
			{
				Name:        "name",
				Type:        "string",
				Note:        "",
				Description: "Name of the extension service.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "Name of the extension service." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "configFiles",
				Type:        "[]ConfigFile",
				Note:        "",
				Description: "The config files for the extension service.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "The config files for the extension service." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "environment",
				Type:        "[]string",
				Note:        "",
				Description: "The environment for the extension service.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "The environment for the extension service." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "selinux",
				Type:        "ServiceSELinux",
				Note:        "",
				Description: "SELinux settings of the extension service, ignored for a service in host runner mode.\nA change of the settings restarts the service.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "SELinux settings of the extension service, ignored for a service in host runner mode." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	doc.AddExample("", extensionServiceConfigV1Alpha1())

	return doc
}

func (ServiceSELinux) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "ServiceSELinux",
		Comments:    [3]string{"" /* encoder.HeadComment */, "ServiceSELinux is the SELinux settings of an extension service." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "ServiceSELinux is the SELinux settings of an extension service.",
		AppearsIn: []encoder.Appearance{
			{
				TypeName:  "ServiceConfigV1Alpha1",
				FieldName: "selinux",
			},
		},
		Fields: []encoder.Doc{
			{
				Name:        "type",
				Type:        "string",
				Note:        "",
				Description: "SELinux type the service runs as, in place of the type Talos derives from the service spec.\n`ext_t` and `ext_privileged_t` come with the base policy, any other is declared by a SELinuxPolicyConfig\ndocument with the `ext_domain` or `ext_privileged_domain` macro. The service waits for the type to be defined\nin the loaded policy before it starts: `talosctl service ext-<name>` says so.\nThe state directories keep the types derived from the spec, `ext_<name>_state_t` and `ext_<name>_run_t`:\n`ext_t` and `ext_privileged_t` reach the state of every service, a type of a document what it is allowed.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "SELinux type the service runs as, in place of the type Talos derives from the service spec." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "audit",
				Type:        "bool",
				Note:        "",
				Description: "Observe the permissions the service exercises: the SELinuxDomainStatus of its type lists the accesses the\npolicy grants it, exercised or not since the audit began, and a policy module narrowed to the exercised ones.\nThe service restarts when the flag is set, so that the accesses of its start are observed.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "Observe the permissions the service exercises: the SELinuxDomainStatus of its type lists the accesses the" /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	doc.Fields[0].AddExample("", "ext_privileged_t")

	return doc
}

func (ConfigFile) Doc() *encoder.Doc {
	doc := &encoder.Doc{
		Type:        "ConfigFile",
		Comments:    [3]string{"" /* encoder.HeadComment */, "ConfigFile is a config file for extension services." /* encoder.LineComment */, "" /* encoder.FootComment */},
		Description: "ConfigFile is a config file for extension services.",
		AppearsIn: []encoder.Appearance{
			{
				TypeName:  "ServiceConfigV1Alpha1",
				FieldName: "configFiles",
			},
		},
		Fields: []encoder.Doc{
			{
				Name:        "content",
				Type:        "string",
				Note:        "",
				Description: "The content of the extension service config file.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "The content of the extension service config file." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
			{
				Name:        "mountPath",
				Type:        "string",
				Note:        "",
				Description: "The mount path of the extension service config file.",
				Comments:    [3]string{"" /* encoder.HeadComment */, "The mount path of the extension service config file." /* encoder.LineComment */, "" /* encoder.FootComment */},
			},
		},
	}

	return doc
}

// GetFileDoc returns documentation for the file extensions_doc.go.
func GetFileDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "extensions",
		Description: "Package extensions provides extensions config documents.\n",
		Structs: []*encoder.Doc{
			ServiceConfigV1Alpha1{}.Doc(),
			ServiceSELinux{}.Doc(),
			ConfigFile{}.Doc(),
		},
	}
}
